apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "ylz-xyz-project-svc-config-xpoo"
  namespace: "default"
  labels:
    app: "ylz-xyz-project-svc"
data:
  API_PREFIX: "/api"
  NODE_ENV: "prod"
  PORT: "3000"
  IAM_SERVICE_URI: "http://localhost:4000"
  DEVICE_SERVICE_URI: "http://localhost:5000"
  FIRESTORE_TYPE: "service_account"
  FIRESTORE_PROJECT_ID: "ylz-xyz-infra"
  FIRESTORE_PRIVATE_KEY_ID: "2e82a9551f6cd1523ac5d1b379f3774237b321c9"
  FIRESTORE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3yeELiHkpd1qP\nHwNO2s4/iHVGXYYHgbU0CJuQ8Dx41N5aFWTIJTfu9/CausOVTVwNNmy91JusyglL\ncGkfgOTqTsvtrc5Qf+reEJOfeHWcyJDu4r2VYB6O48RAm517YLTbpjodujpLFuwD\nGsOsiQZSialaRgswP5G+BfWabrCvSJFAJX+XCy4K6fIDwP7HzKjOKzN7MEOscfpw\nZRJIsHvE2Wu4COl+2pZAc1SaHVBYJ9Rm3SAFY+Ykl4MGyV5IoIdzewjntQvprK5m\naCtegnqULSgQgtOllM/0NGyFj9CcMui0w145nASqHFzW7gQ4QDtIhIfVbhpD+Wpg\nU8DfPTwFAgMBAAECggEAH55KyePm6lAXA4/Tjx2cBXiZqmsdC44QST0g3FDEKop+\nnVNYZQloI8PCgDAYxUcLitdd4lOhG5sfebvDThDr8PZw5Xk1CQrUsnL6HqGH5Frp\n+jsGYBwq7ay4HuBWubrTqoUgsuwOqsvs+wS//J8POCRoPvhVZO3Oyjj2vaSE34aq\ntWap1OJaQiqgDtwj6xHiRIUu8hTLliRvLfBO1YYIZ3hwX0RSF5rOx0sgzM/x37yJ\nRllSCrKEYOekFBafDRPw8jCz+VMJcO9oqu45n+sjtKhnPPFJSTrft7Zh7OizNiKm\nwd8+rdcOooZ4KJkJ8mQg7oOaPognHN4m1L4QX8ELAQKBgQDwXIdPReRLEsYoTeoC\nAvKLSzvoBY89caXP01zukcqXqpykdyW2wDWzKbaGxykq6AfAjXrXeigy4oX6VJaZ\nnD4BvypHZwTHM76lpMl3MfbQ4o+SOHscOOxNGoubG0iPq/0drtMocHBsEj4xTze2\nCzxv1FZ828ZI7U2gEaY4Vz7XBQKBgQDDvxILYqAXb5LrzCS/bMxqh/K36ZeniwWJ\nRTCVVkzPvb0EeXW1lmI293lZZZBbR7vsQNEvifdNtYPCtCV+YMOWk8q+YUrJDQgr\n9CL8QtM6ZUKD+O4VFa5JBGC1I9qjgFwZj7RbYmY9Ug0qnVz1MykgdGaEZtfsBGWg\nHIMgwmfhAQKBgEz8Zf53FWMSVVPNeNlCFmuVIk/zj+iPQRuqyEZFfg1MATYQT40U\nTV7gSm0q1z296dW7uw/POZbqxRzkAQScbaPjlege0AH5yeOGP10lLLfFCVU9L/lf\nJhigGv0IJRqXbNAYEdwO/4Mt6KukguSU/ruW2EjPn9f14foWDRZYo3D9AoGAQzQC\nGe6OT/16T4ISy7WqqJhr+EA2VMsh53Ldryelz1yw3CxnASTUK1LjUpHP8ca6+e12\n4/9V7FP5HIuEo9LM05GB9cKpTkUvHQgASuMWaeIB6BU6h/qdj2v1V7srgR68f/oa\nTZWGzF6zLoJAO96IrB/KYoJ8dwc7bLDdRA36ZAECgYEA4ggN3Y4cfZ5otrmD+3QD\nbfzhVeB4tmtQp7QZLxdZL+OYdvq2JN6OuVyBFVJfIE+PwjqE7GlfrrneSbmwjeE+\nKuN64NuWZbgriVi8zY+LdmD1zC/OyMM0MaqS13eDhfFXihs//81AibAJGZVfIjtv\nyd/zeQegIhdiy3gZ40FAAv0=\n-----END PRIVATE KEY-----\n"
  FIRESTORE_CLIENT_EMAIL: "firebase-adminsdk-4ohxx@ylz-xyz-infra.iam.gserviceaccount.com"
  FIRESTORE_CLIENT_ID: "110921252061653476098"
  FIRESTORE_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  FIRESTORE_TOKEN_URI: "https://oauth2.googleapis.com/token"
  FIRESTORE_AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  FIRESTORE_CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4ohxx%40ylz-xyz-infra.iam.gserviceaccount.com"