apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ylz-xyz-project-svc
  name: ylz-xyz-project-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ylz-xyz-project-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ylz-xyz-project-svc
    spec:
      containers:
        - env:
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: API_PREFIX
                  name: ylz-xyz-project-svc-config-orzw
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: ylz-xyz-project-svc-config-orzw
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_TYPE
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_TYPE
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_PROJECT_ID
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_PRIVATE_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_PRIVATE_KEY_ID
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_PRIVATE_KEY
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_CLIENT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_CLIENT_EMAIL
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_CLIENT_ID
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_AUTH_URI
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_TOKEN_URI
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_TOKEN_URI
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
                  name: ylz-xyz-project-svc-config-orzw
            - name: FIRESTORE_CLIENT_X509_CERT_URL
              valueFrom:
                configMapKeyRef:
                  key: FIRESTORE_CLIENT_X509_CERT_URL
                  name: ylz-xyz-project-svc-config-orzw
          image: gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-project-svc
          imagePullPolicy: IfNotPresent
          name: ylz-xyz-project-svc-1