apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    gcb-build-id: 6dedb31c-5265-4b04-af41-86ecee790c12
    gcb-trigger-id: 70e24674-6321-4537-a91e-166a964211d8
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"gcb-build-id":"6dedb31c-5265-4b04-af41-86ecee790c12","gcb-trigger-id":"70e24674-6321-4537-a91e-166a964211d8"},"labels":{"app":"ylz-xyz-project-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-project-svc","app.kubernetes.io/version":"e9d5c10a330d26a064f1b18cdad849b60a6d0a5b"},"name":"ylz-xyz-project-svc","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ylz-xyz-project-svc"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"6dedb31c-5265-4b04-af41-86ecee790c12","gcb-trigger-id":"70e24674-6321-4537-a91e-166a964211d8"},"labels":{"app":"ylz-xyz-project-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-project-svc","app.kubernetes.io/version":"e9d5c10a330d26a064f1b18cdad849b60a6d0a5b"}},"spec":{"containers":[{"env":[{"name":"API_PREFIX","valueFrom":{"configMapKeyRef":{"key":"API_PREFIX","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"NODE_ENV","valueFrom":{"configMapKeyRef":{"key":"NODE_ENV","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"PORT","valueFrom":{"configMapKeyRef":{"key":"PORT","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_TYPE","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TYPE","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_PROJECT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PROJECT_ID","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_PRIVATE_KEY_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY_ID","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_PRIVATE_KEY","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_CLIENT_EMAIL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_EMAIL","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_CLIENT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_ID","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_AUTH_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_URI","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_TOKEN_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TOKEN_URI","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","name":"ylz-xyz-project-svc-config-orzw"}}},{"name":"FIRESTORE_CLIENT_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_X509_CERT_URL","name":"ylz-xyz-project-svc-config-orzw"}}}],"image":"gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-project-svc@sha256:71b4018a07b26d2e92074babcf2f46b6170e95da29feb3c349527a78398fa379","imagePullPolicy":"IfNotPresent","name":"ylz-xyz-project-svc-1"}]}}}}
  creationTimestamp: "2020-03-17T13:36:28Z"
  generation: 14
  labels:
    app: ylz-xyz-project-svc
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: ylz-xyz-project-svc
    app.kubernetes.io/version: e9d5c10a330d26a064f1b18cdad849b60a6d0a5b
  name: ylz-xyz-project-svc
  namespace: default
  resourceVersion: "323650"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ylz-xyz-project-svc
  uid: 4dea69f9-6854-11ea-b055-42010a9c00b1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ylz-xyz-project-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: 6dedb31c-5265-4b04-af41-86ecee790c12
        gcb-trigger-id: 70e24674-6321-4537-a91e-166a964211d8
      creationTimestamp: null
      labels:
        app: ylz-xyz-project-svc
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: ylz-xyz-project-svc
        app.kubernetes.io/version: e9d5c10a330d26a064f1b18cdad849b60a6d0a5b
    spec:
      containers:
      - env:
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              key: API_PREFIX
              name: ylz-xyz-project-svc-config-orzw
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: ylz-xyz-project-svc-config-orzw
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_TYPE
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TYPE
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PROJECT_ID
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_PRIVATE_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY_ID
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_CLIENT_EMAIL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_EMAIL
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_ID
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_URI
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_TOKEN_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TOKEN_URI
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
              name: ylz-xyz-project-svc-config-orzw
        - name: FIRESTORE_CLIENT_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_X509_CERT_URL
              name: ylz-xyz-project-svc-config-orzw
        image: gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-project-svc@sha256:71b4018a07b26d2e92074babcf2f46b6170e95da29feb3c349527a78398fa379
        imagePullPolicy: IfNotPresent
        name: ylz-xyz-project-svc-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-03-17T13:36:28Z"
    lastUpdateTime: "2020-03-17T17:41:43Z"
    message: ReplicaSet "ylz-xyz-project-svc-77bc87b76d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-17T17:41:58Z"
    lastUpdateTime: "2020-03-17T17:41:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
