apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ylz-xyz-project-svc"
  namespace: "default"
  labels:
    app: "ylz-xyz-project-svc"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "ylz-xyz-project-svc"
  template:
    metadata:
      labels:
        app: "ylz-xyz-project-svc"
    spec:
      containers:
      - name: "ylz-xyz-project-svc"
        image: "$COMMIT_IMAGE_NAME"
