apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ylz-xyz-project-svc-hpa-ot5e"
  namespace: "default"
  labels:
    app: "ylz-xyz-project-svc"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ylz-xyz-project-svc"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80